spring.application.name=InventoryService
server.port=8082

spring.datasource.url=jdbc:mysql://c-int-d000t.cf8mu0ok4vus.eu-north-1.rds.amazonaws.com:3306/c-int-d000t
spring.datasource.username=admin
spring.datasource.password=gR0zgxyeelmPvx2iwCSu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework=INFO
